# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: templateGRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12templateGRPC.proto\"%\n\x13TemplateGRPCRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"%\n\x14TemplateGRPCResponse\x12\r\n\x05reply\x18\x01 \x01(\t2S\n\x0cTemplateGRPC\x12\x43\n\x14TemplateGRPCEndpoint\x12\x14.TemplateGRPCRequest\x1a\x15.TemplateGRPCResponseB\x0b\n\tmahb.grpcb\x06proto3')



_TEMPLATEGRPCREQUEST = DESCRIPTOR.message_types_by_name['TemplateGRPCRequest']
_TEMPLATEGRPCRESPONSE = DESCRIPTOR.message_types_by_name['TemplateGRPCResponse']
TemplateGRPCRequest = _reflection.GeneratedProtocolMessageType('TemplateGRPCRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPLATEGRPCREQUEST,
  '__module__' : 'templateGRPC_pb2'
  # @@protoc_insertion_point(class_scope:TemplateGRPCRequest)
  })
_sym_db.RegisterMessage(TemplateGRPCRequest)

TemplateGRPCResponse = _reflection.GeneratedProtocolMessageType('TemplateGRPCResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEMPLATEGRPCRESPONSE,
  '__module__' : 'templateGRPC_pb2'
  # @@protoc_insertion_point(class_scope:TemplateGRPCResponse)
  })
_sym_db.RegisterMessage(TemplateGRPCResponse)

_TEMPLATEGRPC = DESCRIPTOR.services_by_name['TemplateGRPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\tmahb.grpc'
  _TEMPLATEGRPCREQUEST._serialized_start=22
  _TEMPLATEGRPCREQUEST._serialized_end=59
  _TEMPLATEGRPCRESPONSE._serialized_start=61
  _TEMPLATEGRPCRESPONSE._serialized_end=98
  _TEMPLATEGRPC._serialized_start=100
  _TEMPLATEGRPC._serialized_end=183
# @@protoc_insertion_point(module_scope)
